server:
  port: 7001
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: eureka-server